"""baseline schema initial

Revision ID: 8470b4956f15
Revises: 
Create Date: 2026-06-14 05:32:24.636973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8470b4956f15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prix_mensuel', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_salaries', sa.Integer(), nullable=True),
    sa.Column('max_utilisateurs', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('rubriques_paie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('taux_salarie', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('taux_patronal', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('plafond_mensuel', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('denomination', sa.String(length=200), nullable=False),
    sa.Column('sigle', sa.String(length=50), nullable=True),
    sa.Column('activite', sa.String(length=200), nullable=True),
    sa.Column('secteur', sa.String(length=200), nullable=True),
    sa.Column('nif', sa.String(length=50), nullable=True),
    sa.Column('numero_cnss', sa.String(length=50), nullable=True),
    sa.Column('numero_cnamgs', sa.String(length=50), nullable=True),
    sa.Column('adresse', sa.String(length=300), nullable=True),
    sa.Column('boite_postale', sa.String(length=20), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_inscription', sa.DateTime(), nullable=True),
    sa.Column('date_expiration', sa.DateTime(), nullable=True),
    sa.Column('token_api', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('modele_bulletin', sa.String(length=30), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('langue', sa.String(length=5), nullable=True),
    sa.Column('convention', sa.String(length=20), nullable=True),
    sa.Column('jours_conge_par_mois', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('token_api')
    )
    op.create_table('categories_emploi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=True),
    sa.Column('salaire_minimum', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code')
    )
    op.create_table('journaliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('taux_horaire', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_embauche', sa.Date(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('nationalite', sa.String(length=60), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_secret', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('derniere_utilisation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    with op.batch_alter_table('oauth_clients', schema=None) as batch_op:
        batch_op.create_index('idx_oauth_client_id', ['client_id'], unique=False)
        batch_op.create_index('idx_oauth_tenant', ['tenant_id'], unique=False)

    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('moyen', sa.String(length=30), nullable=False),
    sa.Column('montant', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('duree_mois', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('reference_interne', sa.String(length=100), nullable=False),
    sa.Column('reference_externe', sa.String(length=200), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_confirmation', sa.DateTime(), nullable=True),
    sa.Column('reponse_raw', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_interne')
    )
    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.create_index('idx_paiements_statut', ['statut'], unique=False)
        batch_op.create_index('idx_paiements_tenant', ['tenant_id', 'date_creation'], unique=False)

    op.create_table('periodes_paie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('libelle_mois', sa.String(length=20), nullable=False),
    sa.Column('trimestre', sa.String(length=10), nullable=True),
    sa.Column('date_ouverture', sa.DateTime(), nullable=True),
    sa.Column('date_cloture', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'annee', 'mois')
    )
    op.create_table('prestataires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type_personne', sa.String(length=10), nullable=True),
    sa.Column('categorie', sa.String(length=20), nullable=True),
    sa.Column('raison_sociale', sa.String(length=200), nullable=False),
    sa.Column('sigle', sa.String(length=50), nullable=True),
    sa.Column('nom_contact', sa.String(length=200), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('adresse', sa.String(length=300), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('nif', sa.String(length=50), nullable=True),
    sa.Column('rccm', sa.String(length=50), nullable=True),
    sa.Column('cnss_employeur', sa.String(length=30), nullable=True),
    sa.Column('activite', sa.String(length=200), nullable=True),
    sa.Column('mode_paiement', sa.String(length=30), nullable=True),
    sa.Column('rib', sa.String(length=50), nullable=True),
    sa.Column('banque', sa.String(length=100), nullable=True),
    sa.Column('numero_mobile_money', sa.String(length=30), nullable=True),
    sa.Column('resident', sa.Boolean(), nullable=True),
    sa.Column('assujetti_tva', sa.Boolean(), nullable=True),
    sa.Column('taux_retenue_source', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code')
    )
    with op.batch_alter_table('prestataires', schema=None) as batch_op:
        batch_op.create_index('idx_prestataires_tenant_cat', ['tenant_id', 'categorie'], unique=False)
        batch_op.create_index('idx_prestataires_tenant_statut', ['tenant_id', 'statut'], unique=False)

    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('adresse', sa.String(length=300), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('responsable', sa.String(length=200), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=200), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('email_verifie', sa.Boolean(), nullable=True),
    sa.Column('token_confirmation', sa.String(length=200), nullable=True),
    sa.Column('token_confirmation_expiry', sa.DateTime(), nullable=True),
    sa.Column('nouvel_email_en_attente', sa.String(length=200), nullable=True),
    sa.Column('token_changement_email', sa.String(length=200), nullable=True),
    sa.Column('token_changement_expiry', sa.DateTime(), nullable=True),
    sa.Column('derniere_activite', sa.DateTime(), nullable=True),
    sa.Column('nb_echecs_connexion', sa.Integer(), nullable=True),
    sa.Column('compte_bloque_jusqu', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entite', sa.String(length=50), nullable=True),
    sa.Column('entite_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('avant', sa.Text(), nullable=True),
    sa.Column('apres', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('date_action', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_entite', ['entite', 'entite_id'], unique=False)
        batch_op.create_index('idx_audit_tenant_date', ['tenant_id', 'date_action'], unique=False)
        batch_op.create_index('idx_audit_user', ['user_id', 'date_action'], unique=False)

    op.create_table('contrats_prestation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('prestataire_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('objet', sa.String(length=300), nullable=False),
    sa.Column('type_remuneration', sa.String(length=20), nullable=True),
    sa.Column('montant', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('devise', sa.String(length=5), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prestataire_id'], ['prestataires.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contrats_prestation', schema=None) as batch_op:
        batch_op.create_index('idx_contrats_prest_tenant', ['tenant_id', 'prestataire_id'], unique=False)

    op.create_table('feuilles_paie_journalier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('journalier_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('nb_jours', sa.Integer(), nullable=True),
    sa.Column('total_heures', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('taux_horaire', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('montant_brut', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('observation', sa.String(length=200), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journalier_id'], ['journaliers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('adresse', sa.String(length=300), nullable=True),
    sa.Column('nationalite', sa.String(length=100), nullable=True),
    sa.Column('sexe', sa.String(length=1), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('date_embauche', sa.Date(), nullable=False),
    sa.Column('date_cessation', sa.Date(), nullable=True),
    sa.Column('situation_matrimoniale', sa.String(length=50), nullable=True),
    sa.Column('nb_enfants', sa.Integer(), nullable=True),
    sa.Column('nb_enfants_moins_16ans', sa.Integer(), nullable=True),
    sa.Column('nombre_parts', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('numero_cnss', sa.String(length=30), nullable=True),
    sa.Column('numero_cnamgs', sa.String(length=30), nullable=True),
    sa.Column('emploi', sa.String(length=200), nullable=True),
    sa.Column('assujetti_cnamgs', sa.Boolean(), nullable=True),
    sa.Column('type_rupture', sa.String(length=100), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories_emploi.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'matricule')
    )
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.create_index('idx_salaries_tenant_embauche', ['tenant_id', 'date_embauche'], unique=False)
        batch_op.create_index('idx_salaries_tenant_statut', ['tenant_id', 'statut'], unique=False)

    op.create_table('acomptes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('salarie_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('date_acompte', sa.Date(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('motif', sa.String(length=200), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salarie_id'], ['salaries.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affectations_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('salarie_id', sa.Integer(), nullable=True),
    sa.Column('journalier_id', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('motif', sa.String(length=300), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('cree_par', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['journalier_id'], ['journaliers.id'], ),
    sa.ForeignKeyConstraint(['salarie_id'], ['salaries.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulletins_paie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('salarie_id', sa.Integer(), nullable=False),
    sa.Column('periode_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('numero_seq', sa.Integer(), nullable=True),
    sa.Column('nb_jours_travailles', sa.Integer(), nullable=True),
    sa.Column('salaire_base', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('heures_sup_10', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('heures_sup_30', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('heures_sup_40', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('heures_sup_70', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('absences', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sursalaire', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('prime_caisse', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('carburant', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('prime_anciennete', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('indem_logement', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('indem_domesticite', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('indem_eau_electricite', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('indem_nourriture', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('prime_rendement', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('prime_assiduité', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('prime_qualite', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('prime_performance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('prime_transport', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('prime_responsabilite', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('allocations_conge', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('indem_compensatrice_conge', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('indem_services_rendus', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('indem_compensatrice_preavis', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('indem_licenciement', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('salaire_brut', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('base_cnss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cnss_salarie', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cnss_patronale', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('base_cnamgs', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cnamgs_salarie', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cnamgs_patronale', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fnh', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cfp', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('base_tcs', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tcs', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('base_irpp', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('irpp', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_avant_irpp', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('salaire_net', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('prime_panier', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('indem_transport', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('indem_representation', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('prime_salisure', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('acompte', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_a_payer', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('base_salaire_base', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_salaire_base', sa.String(length=20), nullable=True),
    sa.Column('base_heures_sup_10', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_heures_sup_10', sa.String(length=20), nullable=True),
    sa.Column('base_heures_sup_30', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_heures_sup_30', sa.String(length=20), nullable=True),
    sa.Column('base_heures_sup_40', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_heures_sup_40', sa.String(length=20), nullable=True),
    sa.Column('base_heures_sup_70', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_heures_sup_70', sa.String(length=20), nullable=True),
    sa.Column('base_absences', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_absences', sa.String(length=20), nullable=True),
    sa.Column('base_sursalaire', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_sursalaire', sa.String(length=20), nullable=True),
    sa.Column('base_prime_caisse', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_prime_caisse', sa.String(length=20), nullable=True),
    sa.Column('base_carburant', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_carburant', sa.String(length=20), nullable=True),
    sa.Column('base_prime_anciennete', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_prime_anciennete', sa.String(length=20), nullable=True),
    sa.Column('base_indem_logement', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_indem_logement', sa.String(length=20), nullable=True),
    sa.Column('base_indem_domesticite', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_indem_domesticite', sa.String(length=20), nullable=True),
    sa.Column('base_indem_eau_electricite', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_indem_eau_electricite', sa.String(length=20), nullable=True),
    sa.Column('base_indem_nourriture', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_indem_nourriture', sa.String(length=20), nullable=True),
    sa.Column('base_prime_transport', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_prime_transport', sa.String(length=20), nullable=True),
    sa.Column('base_prime_responsabilite', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_prime_responsabilite', sa.String(length=20), nullable=True),
    sa.Column('base_prime_rendement', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_prime_rendement', sa.String(length=20), nullable=True),
    sa.Column('base_prime_assiduité', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_prime_assiduité', sa.String(length=20), nullable=True),
    sa.Column('base_prime_qualite', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_prime_qualite', sa.String(length=20), nullable=True),
    sa.Column('base_prime_performance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_prime_performance', sa.String(length=20), nullable=True),
    sa.Column('base_allocations_conge', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_allocations_conge', sa.String(length=20), nullable=True),
    sa.Column('base_indem_compensatrice_conge', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_indem_compensatrice_conge', sa.String(length=20), nullable=True),
    sa.Column('base_indem_services_rendus', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_indem_services_rendus', sa.String(length=20), nullable=True),
    sa.Column('base_indem_compensatrice_preavis', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_indem_compensatrice_preavis', sa.String(length=20), nullable=True),
    sa.Column('base_indem_licenciement', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_indem_licenciement', sa.String(length=20), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['periode_id'], ['periodes_paie.id'], ),
    sa.ForeignKeyConstraint(['salarie_id'], ['salaries.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'numero', name='uq_bulletin_numero'),
    sa.UniqueConstraint('tenant_id', 'salarie_id', 'periode_id')
    )
    with op.batch_alter_table('bulletins_paie', schema=None) as batch_op:
        batch_op.create_index('idx_bulletins_tenant_periode', ['tenant_id', 'periode_id'], unique=False)
        batch_op.create_index('idx_bulletins_tenant_statut', ['tenant_id', 'statut'], unique=False)

    op.create_table('conges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('salarie_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('jours_acquis', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('jours_pris', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('date_depart', sa.Date(), nullable=True),
    sa.Column('date_retour', sa.Date(), nullable=True),
    sa.Column('type_conge', sa.String(length=50), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['salarie_id'], ['salaries.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('salarie_id', sa.Integer(), nullable=False),
    sa.Column('type_contrat', sa.String(length=50), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('salaire_base', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('poste', sa.String(length=200), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories_emploi.id'], ),
    sa.ForeignKeyConstraint(['salarie_id'], ['salaries.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factures_prestataire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('prestataire_id', sa.Integer(), nullable=False),
    sa.Column('contrat_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('date_facture', sa.Date(), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('montant_ht', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('taux_tva', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('montant_tva', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taux_retenue', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('montant_retenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('montant_ttc', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('montant_net_a_payer', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('montant_paye', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats_prestation.id'], ),
    sa.ForeignKeyConstraint(['prestataire_id'], ['prestataires.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'prestataire_id', 'numero')
    )
    with op.batch_alter_table('factures_prestataire', schema=None) as batch_op:
        batch_op.create_index('idx_factures_tenant_date', ['tenant_id', 'date_facture'], unique=False)
        batch_op.create_index('idx_factures_tenant_statut', ['tenant_id', 'statut'], unique=False)

    op.create_table('pointages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('date_pointage', sa.Date(), nullable=False),
    sa.Column('salarie_id', sa.Integer(), nullable=True),
    sa.Column('journalier_id', sa.Integer(), nullable=True),
    sa.Column('present', sa.Boolean(), nullable=True),
    sa.Column('heures_normales', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('heures_sup', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('heures_sup_10', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('heures_sup_30', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('heures_sup_40', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('heures_sup_70', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('absent', sa.Boolean(), nullable=True),
    sa.Column('motif_absence', sa.String(length=100), nullable=True),
    sa.Column('observation', sa.String(length=200), nullable=True),
    sa.Column('type_jour', sa.String(length=20), nullable=True),
    sa.Column('entree_matin', sa.String(length=5), nullable=True),
    sa.Column('sortie_matin', sa.String(length=5), nullable=True),
    sa.Column('entree_apmidi', sa.String(length=5), nullable=True),
    sa.Column('sortie_apmidi', sa.String(length=5), nullable=True),
    sa.Column('entree_sup', sa.String(length=5), nullable=True),
    sa.Column('sortie_sup', sa.String(length=5), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journalier_id'], ['journaliers.id'], ),
    sa.ForeignKeyConstraint(['salarie_id'], ['salaries.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'date_pointage', 'journalier_id'),
    sa.UniqueConstraint('tenant_id', 'date_pointage', 'salarie_id')
    )
    with op.batch_alter_table('pointages', schema=None) as batch_op:
        batch_op.create_index('idx_pointages_salarie', ['salarie_id', 'date_pointage'], unique=False)
        batch_op.create_index('idx_pointages_tenant_date', ['tenant_id', 'date_pointage'], unique=False)

    op.create_table('paiements_prestataire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=False),
    sa.Column('mode_paiement', sa.String(length=30), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['facture_id'], ['factures_prestataire.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paiements_prestataire', schema=None) as batch_op:
        batch_op.create_index('idx_paiements_prest_tenant', ['tenant_id', 'facture_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiements_prestataire', schema=None) as batch_op:
        batch_op.drop_index('idx_paiements_prest_tenant')

    op.drop_table('paiements_prestataire')
    with op.batch_alter_table('pointages', schema=None) as batch_op:
        batch_op.drop_index('idx_pointages_tenant_date')
        batch_op.drop_index('idx_pointages_salarie')

    op.drop_table('pointages')
    with op.batch_alter_table('factures_prestataire', schema=None) as batch_op:
        batch_op.drop_index('idx_factures_tenant_statut')
        batch_op.drop_index('idx_factures_tenant_date')

    op.drop_table('factures_prestataire')
    op.drop_table('contrats')
    op.drop_table('conges')
    with op.batch_alter_table('bulletins_paie', schema=None) as batch_op:
        batch_op.drop_index('idx_bulletins_tenant_statut')
        batch_op.drop_index('idx_bulletins_tenant_periode')

    op.drop_table('bulletins_paie')
    op.drop_table('affectations_sites')
    op.drop_table('acomptes')
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.drop_index('idx_salaries_tenant_statut')
        batch_op.drop_index('idx_salaries_tenant_embauche')

    op.drop_table('salaries')
    op.drop_table('feuilles_paie_journalier')
    with op.batch_alter_table('contrats_prestation', schema=None) as batch_op:
        batch_op.drop_index('idx_contrats_prest_tenant')

    op.drop_table('contrats_prestation')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_user')
        batch_op.drop_index('idx_audit_tenant_date')
        batch_op.drop_index('idx_audit_entite')
        batch_op.drop_index('idx_audit_action')

    op.drop_table('audit_logs')
    op.drop_table('utilisateurs')
    op.drop_table('sites')
    with op.batch_alter_table('prestataires', schema=None) as batch_op:
        batch_op.drop_index('idx_prestataires_tenant_statut')
        batch_op.drop_index('idx_prestataires_tenant_cat')

    op.drop_table('prestataires')
    op.drop_table('periodes_paie')
    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.drop_index('idx_paiements_tenant')
        batch_op.drop_index('idx_paiements_statut')

    op.drop_table('paiements')
    with op.batch_alter_table('oauth_clients', schema=None) as batch_op:
        batch_op.drop_index('idx_oauth_tenant')
        batch_op.drop_index('idx_oauth_client_id')

    op.drop_table('oauth_clients')
    op.drop_table('journaliers')
    op.drop_table('categories_emploi')
    op.drop_table('tenants')
    op.drop_table('rubriques_paie')
    op.drop_table('plans')
    # ### end Alembic commands ###
